Errors galore
Even after tracing the code to see which functions were causing the
errors I still can't figure out what is wrong. That is, I don't know how
a negative number is being passed as an index...

ArgumentOutOfRangeException: Cannot be negative.
Parameter name: length
System.String.Substring (Int32 startIndex, Int32
length) (at
/Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System/String.cs:348)
PT_XMLReader.ParseTag
(System.String eS, .PT_XMLHashtable eH) (at
Assets/__Scripts/PT_XMLReader.cs:146)
PT_XMLReader.Parse (System.String
eS, .PT_XMLHashtable eH) (at
Assets/__Scripts/PT_XMLReader.cs:55)
PT_XMLReader.ParseTag
(System.String eS, .PT_XMLHashtable eH) (at
Assets/__Scripts/PT_XMLReader.cs:177)
PT_XMLReader.Parse (System.String
eS, .PT_XMLHashtable eH) (at
Assets/__Scripts/PT_XMLReader.cs:55)
PT_XMLReader.Parse (System.String
eS) (at Assets/__Scripts/PT_XMLReader.cs:48)
BartokLayout.ReadLayout
(System.String xmlText) (at
Assets/__Scripts/BartokLayout.cs:33)
Bartok.Start () (at
Assets/__Scripts/Bartok.cs:28)